---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: registry-ingress
  namespace: infraservices
spec:
  ingressClassName: nginx
  rules:
    - host: registry.vava.win
      http:
        paths:
          - backend:
              service:
                name: registry-service
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - registry.vava.win
      secretName: registry-ingress-secret
